spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/letsave
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:/mapper/*.xml

logging:
  file:
    path: /var/log
  level:
    com:
      letsave:
        finance:
          mapper: DEBUG
    org:
      springframework:
        transaction:
          interceptor: TRACE
        security: DEBUG